export const agreementsConstants = {
    AGREEMENTS_LIST_REQUEST = 'AGREEMENTS_LIST_REQUEST',
    AGREEMENTS_LIST_SUCCESS = 'AGREEMENTS_LIST_SUCCESS',
    AGREEMENTS_LIST_FAILURE = 'AGREEMENTS_LIST_FAILURE'

}