export const productsConstants = {
    PRODUCTS_LIST_REQUEST: ' PRODUCTS_LIST_REQUEST',
    PRODUCTS_LIST_SUCCESS: ' PRODUCTS_LIST_SUCCESS',
    PRODUCTS_LIST_FAILURE: ' PRODUCTS_LIST_FAILURE'
};

export const allproductsConstants = {
    ALL_PRODUCTS_LIST_REQUEST: ' ALL_PRODUCTS_LIST_REQUEST',
    ALL_PRODUCTS_LIST_SUCCESS: ' ALL_PRODUCTS_LIST_SUCCESS',
    ALL_PRODUCTS_LIST_FAILURE: ' ALL_PRODUCTS_LIST_FAILURE'
};